name: 'coverage'
on:
    workflow_dispatch:
        
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: hays-linux
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2.3.0
